### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by strich3** [FeatherMC/FeatherPlugin#2]
Hey, i saw the ServerAPI here and wanted it to try it out
but then a error popped up in my BungeeCord

Error loading plugin FeatherPartner
java.lang.ClassNotFoundException: net.digitalingot.featherpartner.platforms.bungee.FeatherBungee
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
    at de.dytanic.cloudnet.wrapper.Wrapper.lambda$startApplication$5(Wrapper.java:487) ~[wrapper.jar:3.4.3-RELEASE-cca9610]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[

**Comment by strich3** [comment]
bungee.yml was already fixed
